import os
from pathlib import Path

libpath = Path("C:\\Program Files")
os.add_dll_directory(libpath)

import pylablib as pll
pll.par["devices/dlls/picam"] = "C:\\Program Files\\Common Files\\Princeton Instruments\\Picam\\Runtime"
from pylablib.devices import PrincetonInstruments
print('a')
cam_list = print(PrincetonInstruments.list_cameras())
print(cam_list)
#print(cam_list.serial_number)
cam = PrincetonInstruments.PicamCamera('748:Demo')

#print(PrincetonInstruments.picam.PicamCamera.get_all_attributes(cam))
print(cam.get_attribute('Readout Control Mode'))
print(cam.get_attribute('Shutter Timing Mode'))

cam.close()

"""
Available attributes for COSMOS-66
Dictionary('ADC Analog Gain': PicamAttribute(name='ADC Analog Gain', kind='Enumeration')
'ADC Bit Depth': PicamAttribute(name='ADC Bit Depth', kind='Integer')
'ADC Quality': PicamAttribute(name='ADC Quality', kind='Enumeration')
'Active Shutter': PicamAttribute(name='Active Shutter', kind='Enumeration')
'Cooling Fan Status': PicamAttribute(name='Cooling Fan Status', kind='Enumeration')
'Correct Pixel Intensity': PicamAttribute(name='Correct Pixel Intensity', kind='Boolean')
'Disable Cooling Fan': PicamAttribute(name='Disable Cooling Fan', kind='Boolean')
'Exact Readout Count Maximum': PicamAttribute(name='Exact Readout Count Maximum', kind='Large Integer')
'Exposure Time': PicamAttribute(name='Exposure Time', kind='Floating Point')
'External Shutter Type': PicamAttribute(name='External Shutter Type', kind='Enumeration')
'Frame Rate Calculation': PicamAttribute(name='Frame Rate Calculation', kind='Floating Point')
'Frame Size': PicamAttribute(name='Frame Size', kind='Integer')
'Frame Stride': PicamAttribute(name='Frame Stride', kind='Integer')
'Frame Tracking Bit Depth': PicamAttribute(name='Frame Tracking Bit Depth', kind='Integer')
'Frames per Readout': PicamAttribute(name='Frames per Readout', kind='Integer')
'Gap Height': PicamAttribute(name='Gap Height', kind='Floating Point')
'Gap Width': PicamAttribute(name='Gap Width', kind='Floating Point')
'Internal Shutter Type': PicamAttribute(name='Internal Shutter Type', kind='Enumeration')
'Invert Output Signal': PicamAttribute(name='Invert Output Signal', kind='Boolean')
'Invert Output Signal-2': PicamAttribute(name='Invert Output Signal-2', kind='Boolean')
'Online Readout Rate Calculation': PicamAttribute(name='Online Readout Rate Calculation', kind='Floating Point')
'Orientation': PicamAttribute(name='Orientation', kind='Enumeration')
'Output Signal': PicamAttribute(name='Output Signal', kind='Enumeration')
'Output Signal-2': PicamAttribute(name='Output Signal-2', kind='Enumeration')
'Pixel Bit Depth': PicamAttribute(name='Pixel Bit Depth', kind='Integer')
'Pixel Format': PicamAttribute(name='Pixel Format', kind='Enumeration')
'Pixel Height': PicamAttribute(name='Pixel Height', kind='Floating Point')
'Pixel Width': PicamAttribute(name='Pixel Width', kind='Floating Point')
'ROIs': PicamAttribute(name='ROIs', kind='ROIs')
'Readout Control Mode': PicamAttribute(name='Readout Control Mode', kind='Enumeration')
'Readout Count': PicamAttribute(name='Readout Count', kind='Large Integer')
'Readout Orientation': PicamAttribute(name='Readout Orientation', kind='Enumeration')
'Readout Rate Calculation': PicamAttribute(name='Readout Rate Calculation', kind='Floating Point')
'Readout Stride': PicamAttribute(name='Readout Stride', kind='Integer')
'Readout Time Calculation': PicamAttribute(name='Readout Time Calculation', kind='Floating Point')
'Sensor Active Bottom Margin': PicamAttribute(name='Sensor Active Bottom Margin', kind='Integer')
'Sensor Active Extended Height': PicamAttribute(name='Sensor Active Extended Height', kind='Integer')
'Sensor Active Height': PicamAttribute(name='Sensor Active Height', kind='Integer')
'Sensor Active Left Margin': PicamAttribute(name='Sensor Active Left Margin', kind='Integer')
'Sensor Active Right Margin': PicamAttribute(name='Sensor Active Right Margin', kind='Integer')
'Sensor Active Top Margin': PicamAttribute(name='Sensor Active Top Margin', kind='Integer')
'Sensor Active Width': PicamAttribute(name='Sensor Active Width', kind='Integer')
'Sensor Masked Bottom Margin': PicamAttribute(name='Sensor Masked Bottom Margin', kind='Integer')
'Sensor Masked Height': PicamAttribute(name='Sensor Masked Height', kind='Integer')
'Sensor Masked Top Margin': PicamAttribute(name='Sensor Masked Top Margin', kind='Integer')
'Sensor Secondary Active Height': PicamAttribute(name='Sensor Secondary Active Height', kind='Integer')
'Sensor Secondary Masked Height': PicamAttribute(name='Sensor Secondary Masked Height', kind='Integer')
'Sensor Temperature Reading': PicamAttribute(name='Sensor Temperature Reading', kind='Floating Point')
'Sensor Temperature Set Point': PicamAttribute(name='Sensor Temperature Set Point', kind='Floating Point')
'Sensor Temperature Status': PicamAttribute(name='Sensor Temperature Status', kind='Enumeration')
'Sensor Type': PicamAttribute(name='Sensor Type', kind='Enumeration')
'Shutter Timing Mode': PicamAttribute(name='Shutter Timing Mode', kind='Enumeration')
'Time Stamp Bit Depth': PicamAttribute(name='Time Stamp Bit Depth', kind='Integer')
'Time Stamp Resolution': PicamAttribute(name='Time Stamp Resolution', kind='Large Integer')
'Time Stamps': PicamAttribute(name='Time Stamps', kind='Enumeration')
'Track Frames': PicamAttribute(name='Track Frames', kind='Boolean')
'Trigger Determination': PicamAttribute(name='Trigger Determination', kind='Enumeration')
'Trigger Response': PicamAttribute(name='Trigger Response', kind='Enumeration'))
"""